# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'climbot5d_data_show.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_climbot5d_Data_show(object):
    def setupUi(self, climbot5d_Data_show):
        climbot5d_Data_show.setObjectName("climbot5d_Data_show")
        climbot5d_Data_show.resize(842, 600)
        # self.pushButton = QtWidgets.QPushButton(climbot5d_Data_show)
        # self.pushButton.setGeometry(QtCore.QRect(180, 0, 70, 30))
        # self.pushButton.setObjectName("pushButton")
        self.pushButton_5 = QtWidgets.QPushButton(climbot5d_Data_show)
        self.pushButton_5.setGeometry(QtCore.QRect(0, 0, 50, 30))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(climbot5d_Data_show)
        self.pushButton_6.setGeometry(QtCore.QRect(510, 500, 70, 60))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_6.setCheckable(True)
        self.listWidget = QtWidgets.QListWidget(climbot5d_Data_show)
        self.listWidget.setGeometry(QtCore.QRect(370, 40, 350, 340))
        self.listWidget.setObjectName("listWidget")
        self.horizontalSlider = QtWidgets.QSlider(climbot5d_Data_show)
        self.horizontalSlider.setGeometry(QtCore.QRect(570, 410, 121, 20))
        self.horizontalSlider.setMaximum(1000)
        self.horizontalSlider.setSingleStep(100)
        self.horizontalSlider.setProperty("value", 20)
        self.horizontalSlider.setTracking(True)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setInvertedAppearance(False)
        self.horizontalSlider.setInvertedControls(False)
        self.horizontalSlider.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.horizontalSlider.setTickInterval(100)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.label = QtWidgets.QLabel(climbot5d_Data_show)
        self.label.setGeometry(QtCore.QRect(610, 430, 40, 20))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(climbot5d_Data_show)
        self.label_2.setGeometry(QtCore.QRect(370, 10, 67, 17))
        self.label_2.setObjectName("label_2")
        self.pushButton_2 = QtWidgets.QPushButton(climbot5d_Data_show)
        self.pushButton_2.setGeometry(QtCore.QRect(370, 500, 70, 60))
        self.pushButton_2.setObjectName("pushButton_2")
        self.textEdit = QtWidgets.QTextEdit(climbot5d_Data_show)
        self.textEdit.setGeometry(QtCore.QRect(13, 39, 341, 511))
        self.textEdit.setObjectName("textEdit")
        self.pushButton_11 = QtWidgets.QPushButton(climbot5d_Data_show)
        self.pushButton_11.setGeometry(QtCore.QRect(730, 40, 100, 60))
        self.pushButton_11.setCheckable(True)
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_12 = QtWidgets.QPushButton(climbot5d_Data_show)
        self.pushButton_12.setGeometry(QtCore.QRect(730, 130, 100, 60))
        self.pushButton_12.setCheckable(True)
        self.pushButton_12.setObjectName("pushButton_12")
        self.pushButton_14 = QtWidgets.QPushButton(climbot5d_Data_show)
        self.pushButton_14.setGeometry(QtCore.QRect(730, 310, 100, 60))
        self.pushButton_14.setCheckable(True)
        self.pushButton_14.setObjectName("pushButton_14")
        self.pushButton_13 = QtWidgets.QPushButton(climbot5d_Data_show)
        self.pushButton_13.setGeometry(QtCore.QRect(730, 220, 100, 60))
        self.pushButton_13.setCheckable(True)
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_3 = QtWidgets.QPushButton(climbot5d_Data_show)
        self.pushButton_3.setGeometry(QtCore.QRect(420, 400, 70, 60))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(climbot5d_Data_show)
        self.pushButton_4.setGeometry(QtCore.QRect(720, 460, 100, 100))
        self.pushButton_4.setStyleSheet("background-color: rgb(239, 41, 41);")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_7 = QtWidgets.QPushButton(climbot5d_Data_show)
        self.pushButton_7.setGeometry(QtCore.QRect(80, 0, 70, 30))
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(climbot5d_Data_show)
        self.pushButton_8.setGeometry(QtCore.QRect(260, 560, 70, 30))
        self.pushButton_8.setObjectName("pushButton_8")

        self.retranslateUi(climbot5d_Data_show)
        # self.listWidget_2.clicked['QModelIndex'].connect(climbot5d_Data_show.get_item)
        self.pushButton_11.clicked['bool'].connect(climbot5d_Data_show.G0_open)
        self.pushButton_12.clicked['bool'].connect(climbot5d_Data_show.G0_close)
        self.pushButton_13.clicked['bool'].connect(climbot5d_Data_show.G6_open)
        self.pushButton_14.clicked['bool'].connect(climbot5d_Data_show.G6_close)
        self.pushButton_3.clicked.connect(climbot5d_Data_show.sent_offline_data)
        self.pushButton_4.clicked.connect(climbot5d_Data_show.quick_stop)
        self.pushButton_7.clicked.connect(climbot5d_Data_show.data_monitor)
        
        # self.pushButton.clicked.connect(climbot5d_Data_show.load_file)
        self.pushButton_5.clicked.connect(climbot5d_Data_show.return_last_ui)
        self.pushButton_6.clicked['bool'].connect(climbot5d_Data_show.pause_data_show)
        self.pushButton_2.clicked.connect(climbot5d_Data_show.start_data_show)
        self.pushButton_8.clicked.connect(climbot5d_Data_show.load_data)

        self.horizontalSlider.valueChanged['int'].connect(climbot5d_Data_show.change_velocity)
        QtCore.QMetaObject.connectSlotsByName(climbot5d_Data_show)

    def retranslateUi(self, climbot5d_Data_show):
        _translate = QtCore.QCoreApplication.translate
        climbot5d_Data_show.setWindowTitle(_translate("climbot5d_Data_show", "数据再现"))
        # self.pushButton.setText(_translate("climbot5d_Data_show", "载入文件"))
        self.pushButton_5.setText(_translate("climbot5d_Data_show", "返回"))
        self.pushButton_6.setText(_translate("climbot5d_Data_show", "暂停"))
        self.label.setText(_translate("climbot5d_Data_show", "速度"))
        self.label_2.setText(_translate("climbot5d_Data_show", "执行过程"))
        self.pushButton_2.setText(_translate("climbot5d_Data_show", "运行"))
        self.pushButton_11.setText(_translate("climbot5d_Data_show", "G0(open)"))
        self.pushButton_12.setText(_translate("climbot5d_Data_show", "G0(close)"))
        self.pushButton_14.setText(_translate("climbot5d_Data_show", "G6(close)"))
        self.pushButton_13.setText(_translate("climbot5d_Data_show", "G6(open)"))
        self.pushButton_3.setText(_translate("climbot5d_Data_show", "插补"))
        self.pushButton_4.setText(_translate("climbot5d_Data_show", "急停"))
        self.pushButton_7.setText(_translate("climbot5d_Data_show", "数据监控"))
        self.pushButton_8.setText(_translate("climbot5d_Data_show", "载入数据"))
