# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'climbot5d_descartes_control.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Climbot5d_Descartes_control(object):
    def setupUi(self, Climbot5d_Descartes_control):
        Climbot5d_Descartes_control.setObjectName("Climbot5d_Descartes_control")
        Climbot5d_Descartes_control.resize(717, 519)
        self.lineEdit_4 = QtWidgets.QLineEdit(Climbot5d_Descartes_control)
        self.lineEdit_4.setGeometry(QtCore.QRect(310, 140, 70, 25))
        self.lineEdit_4.setDragEnabled(True)
        self.lineEdit_4.setReadOnly(True)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label = QtWidgets.QLabel(Climbot5d_Descartes_control)
        self.label.setGeometry(QtCore.QRect(240, 50, 67, 17))
        self.label.setObjectName("label")
        self.label_4 = QtWidgets.QLabel(Climbot5d_Descartes_control)
        self.label_4.setGeometry(QtCore.QRect(240, 140, 67, 17))
        self.label_4.setObjectName("label_4")
        self.pushButton_12 = QtWidgets.QPushButton(Climbot5d_Descartes_control)
        self.pushButton_12.setGeometry(QtCore.QRect(50, 320, 80, 40))
        self.pushButton_12.setCheckable(True)
        self.pushButton_12.setObjectName("pushButton_12")
        self.label_6 = QtWidgets.QLabel(Climbot5d_Descartes_control)
        self.label_6.setGeometry(QtCore.QRect(240, 20, 67, 16))
        self.label_6.setObjectName("label_6")
        self.lineEdit_7 = QtWidgets.QLineEdit(Climbot5d_Descartes_control)
        self.lineEdit_7.setGeometry(QtCore.QRect(310, 200, 70, 25))
        self.lineEdit_7.setDragEnabled(True)
        self.lineEdit_7.setReadOnly(True)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.pushButton_11 = QtWidgets.QPushButton(Climbot5d_Descartes_control)
        self.pushButton_11.setGeometry(QtCore.QRect(50, 260, 80, 40))
        self.pushButton_11.setCheckable(True)
        self.pushButton_11.setObjectName("pushButton_11")
        self.label_3 = QtWidgets.QLabel(Climbot5d_Descartes_control)
        self.label_3.setGeometry(QtCore.QRect(240, 80, 67, 17))
        self.label_3.setObjectName("label_3")
        self.pushButton_3 = QtWidgets.QPushButton(Climbot5d_Descartes_control)
        self.pushButton_3.setGeometry(QtCore.QRect(50, 60, 60, 25))
        self.pushButton_3.setCheckable(True)
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_7 = QtWidgets.QLabel(Climbot5d_Descartes_control)
        self.label_7.setGeometry(QtCore.QRect(240, 200, 67, 17))
        self.label_7.setObjectName("label_7")
        self.pushButton_13 = QtWidgets.QPushButton(Climbot5d_Descartes_control)
        self.pushButton_13.setGeometry(QtCore.QRect(50, 380, 80, 40))
        self.pushButton_13.setCheckable(True)
        self.pushButton_13.setObjectName("pushButton_13")
        self.lineEdit_2 = QtWidgets.QLineEdit(Climbot5d_Descartes_control)
        self.lineEdit_2.setGeometry(QtCore.QRect(310, 50, 70, 25))
        self.lineEdit_2.setDragEnabled(True)
        self.lineEdit_2.setReadOnly(True)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton_5 = QtWidgets.QPushButton(Climbot5d_Descartes_control)
        self.pushButton_5.setGeometry(QtCore.QRect(50, 140, 60, 25))
        self.pushButton_5.setCheckable(True)
        self.pushButton_5.setObjectName("pushButton_5")
        self.label_5 = QtWidgets.QLabel(Climbot5d_Descartes_control)
        self.label_5.setGeometry(QtCore.QRect(240, 170, 67, 17))
        self.label_5.setObjectName("label_5")
        self.lineEdit_3 = QtWidgets.QLineEdit(Climbot5d_Descartes_control)
        self.lineEdit_3.setGeometry(QtCore.QRect(310, 80, 70, 25))
        self.lineEdit_3.setDragEnabled(True)
        self.lineEdit_3.setReadOnly(True)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.pushButton_14 = QtWidgets.QPushButton(Climbot5d_Descartes_control)
        self.pushButton_14.setGeometry(QtCore.QRect(50, 440, 80, 40))
        self.pushButton_14.setCheckable(True)
        self.pushButton_14.setObjectName("pushButton_14")
        self.pushButton_4 = QtWidgets.QPushButton(Climbot5d_Descartes_control)
        self.pushButton_4.setGeometry(QtCore.QRect(50, 100, 60, 25))
        self.pushButton_4.setCheckable(True)
        self.pushButton_4.setObjectName("pushButton_4")
        self.label_2 = QtWidgets.QLabel(Climbot5d_Descartes_control)
        self.label_2.setGeometry(QtCore.QRect(240, 110, 67, 17))
        self.label_2.setObjectName("label_2")
        self.pushButton_1 = QtWidgets.QPushButton(Climbot5d_Descartes_control)
        self.pushButton_1.setGeometry(QtCore.QRect(50, 20, 60, 25))
        self.pushButton_1.setCheckable(True)
        self.pushButton_1.setObjectName("pushButton_1")
        self.lineEdit_5 = QtWidgets.QLineEdit(Climbot5d_Descartes_control)
        self.lineEdit_5.setGeometry(QtCore.QRect(310, 110, 70, 25))
        self.lineEdit_5.setDragEnabled(True)
        self.lineEdit_5.setReadOnly(True)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.pushButton_6 = QtWidgets.QPushButton(Climbot5d_Descartes_control)
        self.pushButton_6.setGeometry(QtCore.QRect(50, 180, 60, 25))
        self.pushButton_6.setCheckable(True)
        self.pushButton_6.setObjectName("pushButton_6")
        self.lineEdit_6 = QtWidgets.QLineEdit(Climbot5d_Descartes_control)
        self.lineEdit_6.setGeometry(QtCore.QRect(310, 170, 70, 25))
        self.lineEdit_6.setDragEnabled(True)
        self.lineEdit_6.setReadOnly(True)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.lineEdit = QtWidgets.QLineEdit(Climbot5d_Descartes_control)
        self.lineEdit.setGeometry(QtCore.QRect(310, 20, 70, 25))
        self.lineEdit.setText("")
        self.lineEdit.setDragEnabled(True)
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton_15 = QtWidgets.QPushButton(Climbot5d_Descartes_control)
        self.pushButton_15.setGeometry(QtCore.QRect(50, 220, 60, 25))
        self.pushButton_15.setCheckable(True)
        self.pushButton_15.setObjectName("pushButton_15")
        self.label_9 = QtWidgets.QLabel(Climbot5d_Descartes_control)
        self.label_9.setGeometry(QtCore.QRect(260, 350, 67, 17))
        self.label_9.setObjectName("label_9")
        self.label_11 = QtWidgets.QLabel(Climbot5d_Descartes_control)
        self.label_11.setGeometry(QtCore.QRect(260, 410, 67, 17))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(Climbot5d_Descartes_control)
        self.label_12.setGeometry(QtCore.QRect(260, 290, 67, 17))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(Climbot5d_Descartes_control)
        self.label_13.setGeometry(QtCore.QRect(260, 320, 67, 17))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(Climbot5d_Descartes_control)
        self.label_14.setGeometry(QtCore.QRect(260, 380, 67, 17))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(Climbot5d_Descartes_control)
        self.label_15.setGeometry(QtCore.QRect(260, 260, 67, 17))
        self.label_15.setObjectName("label_15")
        self.lineEdit_8 = QtWidgets.QLineEdit(Climbot5d_Descartes_control)
        self.lineEdit_8.setGeometry(QtCore.QRect(310, 380, 70, 25))
        self.lineEdit_8.setDragEnabled(True)
        self.lineEdit_8.setReadOnly(True)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.lineEdit_9 = QtWidgets.QLineEdit(Climbot5d_Descartes_control)
        self.lineEdit_9.setGeometry(QtCore.QRect(310, 260, 70, 25))
        self.lineEdit_9.setText("")
        self.lineEdit_9.setDragEnabled(True)
        self.lineEdit_9.setReadOnly(True)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.lineEdit_10 = QtWidgets.QLineEdit(Climbot5d_Descartes_control)
        self.lineEdit_10.setGeometry(QtCore.QRect(310, 350, 70, 25))
        self.lineEdit_10.setDragEnabled(True)
        self.lineEdit_10.setReadOnly(True)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.lineEdit_11 = QtWidgets.QLineEdit(Climbot5d_Descartes_control)
        self.lineEdit_11.setGeometry(QtCore.QRect(310, 410, 70, 25))
        self.lineEdit_11.setDragEnabled(True)
        self.lineEdit_11.setReadOnly(True)
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.lineEdit_12 = QtWidgets.QLineEdit(Climbot5d_Descartes_control)
        self.lineEdit_12.setGeometry(QtCore.QRect(310, 320, 70, 25))
        self.lineEdit_12.setDragEnabled(True)
        self.lineEdit_12.setReadOnly(True)
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.lineEdit_13 = QtWidgets.QLineEdit(Climbot5d_Descartes_control)
        self.lineEdit_13.setGeometry(QtCore.QRect(310, 290, 70, 25))
        self.lineEdit_13.setDragEnabled(True)
        self.lineEdit_13.setReadOnly(True)
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.pushButton = QtWidgets.QPushButton(Climbot5d_Descartes_control)
        self.pushButton.setGeometry(QtCore.QRect(0, 0, 41, 25))
        self.pushButton.setObjectName("pushButton")
        self.verticalSlider = QtWidgets.QSlider(Climbot5d_Descartes_control)
        self.verticalSlider.setGeometry(QtCore.QRect(180, 269, 20, 131))
        self.verticalSlider.setMaximum(100)
        self.verticalSlider.setSingleStep(1)
        self.verticalSlider.setPageStep(10)
        self.verticalSlider.setProperty("value", 20)
        self.verticalSlider.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.verticalSlider.setObjectName("verticalSlider")
        self.label_8 = QtWidgets.QLabel(Climbot5d_Descartes_control)
        self.label_8.setGeometry(QtCore.QRect(180, 430, 31, 17))
        self.label_8.setObjectName("label_8")
        self.label_10 = QtWidgets.QLabel(Climbot5d_Descartes_control)
        self.label_10.setGeometry(QtCore.QRect(390, 200, 40, 17))
        self.label_10.setObjectName("label_10")
        self.label_16 = QtWidgets.QLabel(Climbot5d_Descartes_control)
        self.label_16.setGeometry(QtCore.QRect(390, 260, 40, 17))
        self.label_16.setObjectName("label_16")
        self.listWidget = QtWidgets.QListWidget(Climbot5d_Descartes_control)
        self.listWidget.setGeometry(QtCore.QRect(450, 30, 256, 451))
        self.listWidget.setObjectName("listWidget")
        self.label_17 = QtWidgets.QLabel(Climbot5d_Descartes_control)
        self.label_17.setGeometry(QtCore.QRect(450, 10, 67, 17))
        self.label_17.setObjectName("label_17")
        self.lineEdit_14 = QtWidgets.QLineEdit(Climbot5d_Descartes_control)
        self.lineEdit_14.setGeometry(QtCore.QRect(130, 20, 50, 25))
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.lineEdit_16 = QtWidgets.QLineEdit(Climbot5d_Descartes_control)
        self.lineEdit_16.setGeometry(QtCore.QRect(130, 60, 50, 25))
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.lineEdit_18 = QtWidgets.QLineEdit(Climbot5d_Descartes_control)
        self.lineEdit_18.setGeometry(QtCore.QRect(130, 100, 50, 25))
        self.lineEdit_18.setObjectName("lineEdit_18")
        self.lineEdit_20 = QtWidgets.QLineEdit(Climbot5d_Descartes_control)
        self.lineEdit_20.setGeometry(QtCore.QRect(130, 140, 50, 25))
        self.lineEdit_20.setObjectName("lineEdit_20")
        self.lineEdit_21 = QtWidgets.QLineEdit(Climbot5d_Descartes_control)
        self.lineEdit_21.setGeometry(QtCore.QRect(130, 180, 50, 25))
        self.lineEdit_21.setObjectName("lineEdit_21")
        self.lineEdit_23 = QtWidgets.QLineEdit(Climbot5d_Descartes_control)
        self.lineEdit_23.setGeometry(QtCore.QRect(130, 220, 50, 25))
        self.lineEdit_23.setObjectName("lineEdit_23")
        self.label_18 = QtWidgets.QLabel(Climbot5d_Descartes_control)
        self.label_18.setGeometry(QtCore.QRect(390, 20, 40, 17))
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(Climbot5d_Descartes_control)
        self.label_19.setGeometry(QtCore.QRect(390, 50, 40, 16))
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(Climbot5d_Descartes_control)
        self.label_20.setGeometry(QtCore.QRect(390, 80, 40, 16))
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(Climbot5d_Descartes_control)
        self.label_21.setGeometry(QtCore.QRect(390, 110, 40, 16))
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(Climbot5d_Descartes_control)
        self.label_22.setGeometry(QtCore.QRect(390, 170, 40, 16))
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(Climbot5d_Descartes_control)
        self.label_23.setGeometry(QtCore.QRect(390, 140, 40, 16))
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(Climbot5d_Descartes_control)
        self.label_24.setGeometry(QtCore.QRect(390, 350, 40, 16))
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(Climbot5d_Descartes_control)
        self.label_25.setGeometry(QtCore.QRect(390, 380, 40, 16))
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(Climbot5d_Descartes_control)
        self.label_26.setGeometry(QtCore.QRect(390, 410, 40, 16))
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(Climbot5d_Descartes_control)
        self.label_27.setGeometry(QtCore.QRect(390, 290, 40, 17))
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(Climbot5d_Descartes_control)
        self.label_28.setGeometry(QtCore.QRect(390, 320, 40, 17))
        self.label_28.setObjectName("label_28")
        self.label_30 = QtWidgets.QLabel(Climbot5d_Descartes_control)
        self.label_30.setGeometry(QtCore.QRect(190, 20, 40, 17))
        self.label_30.setObjectName("label_30")
        self.label_31 = QtWidgets.QLabel(Climbot5d_Descartes_control)
        self.label_31.setGeometry(QtCore.QRect(190, 60, 40, 17))
        self.label_31.setObjectName("label_31")
        self.label_32 = QtWidgets.QLabel(Climbot5d_Descartes_control)
        self.label_32.setGeometry(QtCore.QRect(190, 100, 40, 17))
        self.label_32.setObjectName("label_32")
        self.label_35 = QtWidgets.QLabel(Climbot5d_Descartes_control)
        self.label_35.setGeometry(QtCore.QRect(190, 140, 40, 16))
        self.label_35.setObjectName("label_35")
        self.label_37 = QtWidgets.QLabel(Climbot5d_Descartes_control)
        self.label_37.setGeometry(QtCore.QRect(190, 180, 40, 16))
        self.label_37.setObjectName("label_37")
        self.label_39 = QtWidgets.QLabel(Climbot5d_Descartes_control)
        self.label_39.setGeometry(QtCore.QRect(190, 220, 40, 16))
        self.label_39.setObjectName("label_39")
        self.pushButton_2 = QtWidgets.QPushButton(Climbot5d_Descartes_control)
        self.pushButton_2.setGeometry(QtCore.QRect(310, 450, 80, 60))
        self.pushButton_2.setStyleSheet("background-color: rgb(204, 0, 0);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_7 = QtWidgets.QPushButton(Climbot5d_Descartes_control)
        self.pushButton_7.setGeometry(QtCore.QRect(180, 450, 89, 61))
        self.pushButton_7.setObjectName("pushButton_7")

        self.retranslateUi(Climbot5d_Descartes_control)
        self.pushButton_1.clicked['bool'].connect(Climbot5d_Descartes_control.X_data)
        self.pushButton_3.clicked['bool'].connect(Climbot5d_Descartes_control.Y_data)
        self.pushButton_4.clicked['bool'].connect(Climbot5d_Descartes_control.Z_data)
        self.pushButton_5.clicked['bool'].connect(Climbot5d_Descartes_control.RX_data)
        self.pushButton_6.clicked['bool'].connect(Climbot5d_Descartes_control.RY_data)
        self.pushButton_15.clicked['bool'].connect(Climbot5d_Descartes_control.RZ_data)
        self.pushButton_11.clicked['bool'].connect(Climbot5d_Descartes_control.G0_open)
        self.pushButton_12.clicked['bool'].connect(Climbot5d_Descartes_control.G0_close)
        self.pushButton_13.clicked['bool'].connect(Climbot5d_Descartes_control.G6_open)
        self.pushButton_14.clicked['bool'].connect(Climbot5d_Descartes_control.G6_close)
        self.pushButton.clicked.connect(Climbot5d_Descartes_control.return_last_ui)
        self.pushButton_2.clicked.connect(Climbot5d_Descartes_control.quick_stop)
        self.pushButton_7.clicked.connect(Climbot5d_Descartes_control.teach_record)
        self.verticalSlider.valueChanged['int'].connect(Climbot5d_Descartes_control.change_velocity)

        QtCore.QMetaObject.connectSlotsByName(Climbot5d_Descartes_control)

    def retranslateUi(self, Climbot5d_Descartes_control):
        _translate = QtCore.QCoreApplication.translate
        Climbot5d_Descartes_control.setWindowTitle(_translate("Climbot5d_Descartes_control", "笛卡尔空间控制"))
        self.label.setText(_translate("Climbot5d_Descartes_control", "Joint1"))
        self.label_4.setText(_translate("Climbot5d_Descartes_control", "Joint4"))
        self.pushButton_12.setText(_translate("Climbot5d_Descartes_control", "G0(close)"))
        self.label_6.setText(_translate("Climbot5d_Descartes_control", "Gripper0"))
        self.pushButton_11.setText(_translate("Climbot5d_Descartes_control", "G0(open)"))
        self.label_3.setText(_translate("Climbot5d_Descartes_control", "Joint2"))
        self.pushButton_3.setText(_translate("Climbot5d_Descartes_control", "Y"))
        self.label_7.setText(_translate("Climbot5d_Descartes_control", "Gripper6"))
        self.pushButton_13.setText(_translate("Climbot5d_Descartes_control", "G6(open)"))
        self.pushButton_5.setText(_translate("Climbot5d_Descartes_control", "RX"))
        self.label_5.setText(_translate("Climbot5d_Descartes_control", "Joint5"))
        self.pushButton_14.setText(_translate("Climbot5d_Descartes_control", "G6(close)"))
        self.pushButton_4.setText(_translate("Climbot5d_Descartes_control", "Z"))
        self.label_2.setText(_translate("Climbot5d_Descartes_control", "Joint3"))
        self.pushButton_1.setText(_translate("Climbot5d_Descartes_control", "X"))
        self.pushButton_6.setText(_translate("Climbot5d_Descartes_control", "RY"))
        self.pushButton_15.setText(_translate("Climbot5d_Descartes_control", "RZ"))
        self.label_9.setText(_translate("Climbot5d_Descartes_control", "RX"))
        self.label_11.setText(_translate("Climbot5d_Descartes_control", "RZ"))
        self.label_12.setText(_translate("Climbot5d_Descartes_control", "Y"))
        self.label_13.setText(_translate("Climbot5d_Descartes_control", "Z"))
        self.label_14.setText(_translate("Climbot5d_Descartes_control", "RY"))
        self.label_15.setText(_translate("Climbot5d_Descartes_control", "X"))
        self.pushButton.setText(_translate("Climbot5d_Descartes_control", "返回"))
        self.label_8.setText(_translate("Climbot5d_Descartes_control", "速度"))
        self.label_10.setText(_translate("Climbot5d_Descartes_control", "mN.m"))
        self.label_16.setText(_translate("Climbot5d_Descartes_control", "mm"))
        self.label_17.setText(_translate("Climbot5d_Descartes_control", "执行过程"))
        self.label_18.setText(_translate("Climbot5d_Descartes_control", "mN.m"))
        self.label_19.setText(_translate("Climbot5d_Descartes_control", "deg"))
        self.label_20.setText(_translate("Climbot5d_Descartes_control", "deg"))
        self.label_21.setText(_translate("Climbot5d_Descartes_control", "deg"))
        self.label_22.setText(_translate("Climbot5d_Descartes_control", "deg"))
        self.label_23.setText(_translate("Climbot5d_Descartes_control", "deg"))
        self.label_24.setText(_translate("Climbot5d_Descartes_control", "deg"))
        self.label_25.setText(_translate("Climbot5d_Descartes_control", "deg"))
        self.label_26.setText(_translate("Climbot5d_Descartes_control", "deg"))
        self.label_27.setText(_translate("Climbot5d_Descartes_control", "mm"))
        self.label_28.setText(_translate("Climbot5d_Descartes_control", "mm"))
        self.label_30.setText(_translate("Climbot5d_Descartes_control", "mm"))
        self.label_31.setText(_translate("Climbot5d_Descartes_control", "mm"))
        self.label_32.setText(_translate("Climbot5d_Descartes_control", "mm"))
        self.label_35.setText(_translate("Climbot5d_Descartes_control", "deg"))
        self.label_37.setText(_translate("Climbot5d_Descartes_control", "deg"))
        self.label_39.setText(_translate("Climbot5d_Descartes_control", "deg"))
        self.pushButton_2.setText(_translate("Climbot5d_Descartes_control", "急停"))
        self.pushButton_7.setText(_translate("Climbot5d_Descartes_control", "示教记录"))