# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'climbot5d_joint_control.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Climbot5d_joint_control(object):
    def setupUi(self, Climbot5d_joint_control):
        Climbot5d_joint_control.setObjectName("Climbot5d_joint_control")
        Climbot5d_joint_control.resize(809, 434)
        self.pushButton_5 = QtWidgets.QPushButton(Climbot5d_joint_control)
        self.pushButton_5.setGeometry(QtCore.QRect(100, 280, 60, 50))
        self.pushButton_5.setCheckable(True)
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_1 = QtWidgets.QPushButton(Climbot5d_joint_control)
        self.pushButton_1.setGeometry(QtCore.QRect(100, 40, 60, 50))
        self.pushButton_1.setCheckable(True)
        self.pushButton_1.setObjectName("pushButton_1")
        self.pushButton_4 = QtWidgets.QPushButton(Climbot5d_joint_control)
        self.pushButton_4.setGeometry(QtCore.QRect(100, 200, 60, 50))
        self.pushButton_4.setCheckable(True)
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_14 = QtWidgets.QPushButton(Climbot5d_joint_control)
        self.pushButton_14.setGeometry(QtCore.QRect(410, 120, 100, 50))
        self.pushButton_14.setCheckable(True)
        self.pushButton_14.setObjectName("pushButton_14")
        self.pushButton_8 = QtWidgets.QPushButton(Climbot5d_joint_control)
        self.pushButton_8.setGeometry(QtCore.QRect(190, 200, 60, 50))
        self.pushButton_8.setCheckable(True)
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_2 = QtWidgets.QPushButton(Climbot5d_joint_control)
        self.pushButton_2.setGeometry(QtCore.QRect(190, 40, 60, 50))
        self.pushButton_2.setCheckable(True)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_10 = QtWidgets.QPushButton(Climbot5d_joint_control)
        self.pushButton_10.setGeometry(QtCore.QRect(190, 360, 60, 50))
        self.pushButton_10.setCheckable(True)
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_7 = QtWidgets.QPushButton(Climbot5d_joint_control)
        self.pushButton_7.setGeometry(QtCore.QRect(190, 120, 60, 50))
        self.pushButton_7.setCheckable(True)
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_12 = QtWidgets.QPushButton(Climbot5d_joint_control)
        self.pushButton_12.setGeometry(QtCore.QRect(410, 40, 100, 50))
        self.pushButton_12.setCheckable(True)
        self.pushButton_12.setObjectName("pushButton_12")
        self.pushButton_6 = QtWidgets.QPushButton(Climbot5d_joint_control)
        self.pushButton_6.setGeometry(QtCore.QRect(100, 360, 60, 50))
        self.pushButton_6.setCheckable(True)
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_3 = QtWidgets.QPushButton(Climbot5d_joint_control)
        self.pushButton_3.setGeometry(QtCore.QRect(100, 120, 60, 50))
        self.pushButton_3.setCheckable(True)
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_13 = QtWidgets.QPushButton(Climbot5d_joint_control)
        self.pushButton_13.setGeometry(QtCore.QRect(280, 120, 100, 50))
        self.pushButton_13.setCheckable(True)
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_11 = QtWidgets.QPushButton(Climbot5d_joint_control)
        self.pushButton_11.setGeometry(QtCore.QRect(280, 40, 100, 50))
        self.pushButton_11.setCheckable(True)
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_9 = QtWidgets.QPushButton(Climbot5d_joint_control)
        self.pushButton_9.setGeometry(QtCore.QRect(190, 280, 60, 50))
        self.pushButton_9.setCheckable(True)
        self.pushButton_9.setObjectName("pushButton_9")
        self.label = QtWidgets.QLabel(Climbot5d_joint_control)
        self.label.setGeometry(QtCore.QRect(310, 230, 67, 17))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Climbot5d_joint_control)
        self.label_2.setGeometry(QtCore.QRect(310, 290, 67, 17))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Climbot5d_joint_control)
        self.label_3.setGeometry(QtCore.QRect(310, 260, 67, 17))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Climbot5d_joint_control)
        self.label_4.setGeometry(QtCore.QRect(310, 320, 67, 17))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Climbot5d_joint_control)
        self.label_5.setGeometry(QtCore.QRect(310, 350, 67, 17))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Climbot5d_joint_control)
        self.label_6.setGeometry(QtCore.QRect(310, 200, 67, 17))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Climbot5d_joint_control)
        self.label_7.setGeometry(QtCore.QRect(310, 380, 67, 17))
        self.label_7.setObjectName("label_7")
        self.lineEdit = QtWidgets.QLineEdit(Climbot5d_joint_control)
        self.lineEdit.setGeometry(QtCore.QRect(400, 200, 70, 25))
        self.lineEdit.setText("")
        self.lineEdit.setDragEnabled(True)
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(Climbot5d_joint_control)
        self.lineEdit_2.setGeometry(QtCore.QRect(400, 230, 70, 25))
        self.lineEdit_2.setDragEnabled(True)
        self.lineEdit_2.setReadOnly(True)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(Climbot5d_joint_control)
        self.lineEdit_3.setGeometry(QtCore.QRect(400, 260, 70, 25))
        self.lineEdit_3.setDragEnabled(True)
        self.lineEdit_3.setReadOnly(True)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(Climbot5d_joint_control)
        self.lineEdit_4.setGeometry(QtCore.QRect(400, 320, 70, 25))
        self.lineEdit_4.setDragEnabled(True)
        self.lineEdit_4.setReadOnly(True)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(Climbot5d_joint_control)
        self.lineEdit_5.setGeometry(QtCore.QRect(400, 290, 70, 25))
        self.lineEdit_5.setDragEnabled(True)
        self.lineEdit_5.setReadOnly(True)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_6 = QtWidgets.QLineEdit(Climbot5d_joint_control)
        self.lineEdit_6.setGeometry(QtCore.QRect(400, 350, 70, 25))
        self.lineEdit_6.setDragEnabled(True)
        self.lineEdit_6.setReadOnly(True)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.lineEdit_7 = QtWidgets.QLineEdit(Climbot5d_joint_control)
        self.lineEdit_7.setGeometry(QtCore.QRect(400, 380, 70, 25))
        self.lineEdit_7.setDragEnabled(True)
        self.lineEdit_7.setReadOnly(True)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.pushButton = QtWidgets.QPushButton(Climbot5d_joint_control)
        self.pushButton.setGeometry(QtCore.QRect(0, 0, 51, 25))
        self.pushButton.setObjectName("pushButton")

        self.verticalSlider = QtWidgets.QSlider(Climbot5d_joint_control)
        self.verticalSlider.setGeometry(QtCore.QRect(40, 70, 16, 160))
        self.verticalSlider.setMaximum(1000)
        self.verticalSlider.setSingleStep(100)
        self.verticalSlider.setProperty("value", 20)
        self.verticalSlider.setTracking(True)
        self.verticalSlider.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider.setInvertedAppearance(False)
        self.verticalSlider.setInvertedControls(False)
        self.verticalSlider.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.verticalSlider.setTickInterval(100)
        self.verticalSlider.setObjectName("verticalSlider")

        self.label_9 = QtWidgets.QLabel(Climbot5d_joint_control)
        self.label_9.setGeometry(QtCore.QRect(40, 230, 41, 20))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(Climbot5d_joint_control)
        self.label_10.setGeometry(QtCore.QRect(440, 410, 100, 20))
        self.label_10.setObjectName("label_10")
        self.listWidget = QtWidgets.QListWidget(Climbot5d_joint_control)
        self.listWidget.setGeometry(QtCore.QRect(540, 40, 256, 380))
        self.listWidget.setObjectName("listWidget")
        self.label_10 = QtWidgets.QLabel(Climbot5d_joint_control)
        self.label_10.setGeometry(QtCore.QRect(540, 20, 67, 17))
        self.label_10.setObjectName("label_10")
        self.pushButton_15 = QtWidgets.QPushButton(Climbot5d_joint_control)
        self.pushButton_15.setGeometry(QtCore.QRect(100, 0, 89, 25))
        self.pushButton_15.setObjectName("pushButton_15")
        self.pushButton_16 = QtWidgets.QPushButton(Climbot5d_joint_control)
        self.pushButton_16.setGeometry(QtCore.QRect(210, 0, 89, 25))
        self.pushButton_16.setObjectName("pushButton_16")
        self.label_11 = QtWidgets.QLabel(Climbot5d_joint_control)
        self.label_11.setGeometry(QtCore.QRect(480, 380, 50, 17))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(Climbot5d_joint_control)
        self.label_12.setGeometry(QtCore.QRect(480, 230, 30, 17))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(Climbot5d_joint_control)
        self.label_13.setGeometry(QtCore.QRect(480, 260, 30, 17))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(Climbot5d_joint_control)
        self.label_14.setGeometry(QtCore.QRect(480, 290, 30, 17))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(Climbot5d_joint_control)
        self.label_15.setGeometry(QtCore.QRect(480, 320, 30, 17))
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(Climbot5d_joint_control)
        self.label_16.setGeometry(QtCore.QRect(480, 200, 50, 17))
        self.label_16.setObjectName("label_16")

        self.retranslateUi(Climbot5d_joint_control)
        self.pushButton_1.clicked['bool'].connect(Climbot5d_joint_control.I1_add_position)
        self.pushButton_2.clicked['bool'].connect(Climbot5d_joint_control.I1_sub_position)
        self.pushButton_3.clicked['bool'].connect(Climbot5d_joint_control.T2_add_position)
        self.pushButton_7.clicked['bool'].connect(Climbot5d_joint_control.T2_sub_position)
        self.pushButton_4.clicked['bool'].connect(Climbot5d_joint_control.T3_add_position)
        self.pushButton_8.clicked['bool'].connect(Climbot5d_joint_control.T3_sub_position)
        self.pushButton_5.clicked['bool'].connect(Climbot5d_joint_control.T4_add_position)
        self.pushButton_9.clicked['bool'].connect(Climbot5d_joint_control.T4_sub_position)
        self.pushButton_6.clicked['bool'].connect(Climbot5d_joint_control.I5_add_position)
        self.pushButton_10.clicked['bool'].connect(Climbot5d_joint_control.I5_sub_position)
        self.pushButton_11.clicked['bool'].connect(Climbot5d_joint_control.G0_open)
        self.pushButton_12.clicked['bool'].connect(Climbot5d_joint_control.G0_close)
        self.pushButton_13.clicked['bool'].connect(Climbot5d_joint_control.G6_open)
        self.pushButton_14.clicked['bool'].connect(Climbot5d_joint_control.G6_close)
        self.pushButton.clicked.connect(Climbot5d_joint_control.return_last_ui)
        self.verticalSlider.valueChanged['int'].connect(Climbot5d_joint_control.change_velocity)
        self.pushButton_15.clicked.connect(Climbot5d_joint_control.set_zero)
        self.pushButton_16.clicked.connect(Climbot5d_joint_control.return_zero)
        QtCore.QMetaObject.connectSlotsByName(Climbot5d_joint_control)
        
    def retranslateUi(self, Climbot5d_joint_control):
        _translate = QtCore.QCoreApplication.translate
        Climbot5d_joint_control.setWindowTitle(_translate("Climbot5d_joint_control", "关节空间控制"))
        self.pushButton_5.setText(_translate("Climbot5d_joint_control", "T4(+)"))
        self.pushButton_1.setText(_translate("Climbot5d_joint_control", "I1(+)"))
        self.pushButton_4.setText(_translate("Climbot5d_joint_control", "T3(+)"))
        self.pushButton_14.setText(_translate("Climbot5d_joint_control", "G6(close)"))
        self.pushButton_8.setText(_translate("Climbot5d_joint_control", "T3(-)"))
        self.pushButton_2.setText(_translate("Climbot5d_joint_control", "I1(-)"))
        self.pushButton_10.setText(_translate("Climbot5d_joint_control", "I5(-)"))
        self.pushButton_7.setText(_translate("Climbot5d_joint_control", "T2(-)"))
        self.pushButton_12.setText(_translate("Climbot5d_joint_control", "G0(close)"))
        self.pushButton_6.setText(_translate("Climbot5d_joint_control", "I5(+)"))
        self.pushButton_3.setText(_translate("Climbot5d_joint_control", "T2(+)"))
        self.pushButton_13.setText(_translate("Climbot5d_joint_control", "G6(open)"))
        self.pushButton_11.setText(_translate("Climbot5d_joint_control", "G0(open)"))
        self.pushButton_9.setText(_translate("Climbot5d_joint_control", "T4(-)"))

        self.label.setText(_translate("Climbot5d_joint_control", "I1"))
        self.label_2.setText(_translate("Climbot5d_joint_control", "T3"))
        self.label_3.setText(_translate("Climbot5d_joint_control", "T2"))
        self.label_4.setText(_translate("Climbot5d_joint_control", "T4"))
        self.label_5.setText(_translate("Climbot5d_joint_control", "I5"))
        self.label_6.setText(_translate("Climbot5d_joint_control", "G0"))
        self.label_7.setText(_translate("Climbot5d_joint_control", "G6"))

        self.pushButton.setText(_translate("Climbot5d_joint_control", "返回"))
        self.label_9.setText(_translate("Climbot5d_joint_control", "速度"))
        self.label_10.setText(_translate("Climbot5d_joint_control", "(mN.m,Deg)"))
        self.label_10.setText(_translate("Climbot5d_joint_control", "执行过程"))
        self.pushButton_15.setText(_translate("Climbot5d_joint_control", "设置零位"))
        self.pushButton_16.setText(_translate("Climbot5d_joint_control", "回零"))
        self.label_11.setText(_translate("Climbot5d_joint_control", "mN.m"))
        self.label_12.setText(_translate("Climbot5d_joint_control", "deg"))
        self.label_13.setText(_translate("Climbot5d_joint_control", "deg"))
        self.label_14.setText(_translate("Climbot5d_joint_control", "deg"))
        self.label_15.setText(_translate("Climbot5d_joint_control", "deg"))
        self.label_16.setText(_translate("Climbot5d_joint_control", "mN.m"))