# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'arm5d_data_show_monitor.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_arm5d_data_show_monitor(object):
    def setupUi(self, arm5d_data_show_monitor):
        arm5d_data_show_monitor.setObjectName("arm5d_data_show_monitor")
        arm5d_data_show_monitor.resize(384, 249)
        self.label_7 = QtWidgets.QLabel(arm5d_data_show_monitor)
        self.label_7.setGeometry(QtCore.QRect(10, 50, 30, 17))
        self.label_7.setObjectName("label_7")
        self.lineEdit_5 = QtWidgets.QLineEdit(arm5d_data_show_monitor)
        self.lineEdit_5.setGeometry(QtCore.QRect(40, 90, 81, 25))
        self.lineEdit_5.setReadOnly(True)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_3 = QtWidgets.QLineEdit(arm5d_data_show_monitor)
        self.lineEdit_3.setGeometry(QtCore.QRect(40, 50, 81, 25))
        self.lineEdit_3.setReadOnly(True)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_2 = QtWidgets.QLineEdit(arm5d_data_show_monitor)
        self.lineEdit_2.setGeometry(QtCore.QRect(40, 10, 81, 25))
        self.lineEdit_2.setReadOnly(True)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_3 = QtWidgets.QLabel(arm5d_data_show_monitor)
        self.label_3.setGeometry(QtCore.QRect(10, 90, 30, 17))
        self.label_3.setObjectName("label_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(arm5d_data_show_monitor)
        self.lineEdit_4.setGeometry(QtCore.QRect(40, 130, 81, 25))
        self.lineEdit_4.setReadOnly(True)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_6 = QtWidgets.QLineEdit(arm5d_data_show_monitor)
        self.lineEdit_6.setGeometry(QtCore.QRect(40, 170, 81, 25))
        self.lineEdit_6.setReadOnly(True)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.label_4 = QtWidgets.QLabel(arm5d_data_show_monitor)
        self.label_4.setGeometry(QtCore.QRect(10, 130, 30, 17))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(arm5d_data_show_monitor)
        self.label_5.setGeometry(QtCore.QRect(10, 170, 30, 17))
        self.label_5.setObjectName("label_5")
        self.label_2 = QtWidgets.QLabel(arm5d_data_show_monitor)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 30, 17))
        self.label_2.setObjectName("label_2")
        self.label_6 = QtWidgets.QLabel(arm5d_data_show_monitor)
        self.label_6.setGeometry(QtCore.QRect(140, 10, 40, 17))
        self.label_6.setObjectName("label_6")
        self.label_8 = QtWidgets.QLabel(arm5d_data_show_monitor)
        self.label_8.setGeometry(QtCore.QRect(140, 50, 40, 17))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(arm5d_data_show_monitor)
        self.label_9.setGeometry(QtCore.QRect(140, 90, 40, 17))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(arm5d_data_show_monitor)
        self.label_10.setGeometry(QtCore.QRect(140, 130, 40, 17))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(arm5d_data_show_monitor)
        self.label_11.setGeometry(QtCore.QRect(140, 170, 40, 17))
        self.label_11.setObjectName("label_11")
        self.label_16 = QtWidgets.QLabel(arm5d_data_show_monitor)
        self.label_16.setGeometry(QtCore.QRect(220, 10, 30, 17))
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(arm5d_data_show_monitor)
        self.label_17.setGeometry(QtCore.QRect(220, 170, 30, 17))
        self.label_17.setObjectName("label_17")
        self.lineEdit_7 = QtWidgets.QLineEdit(arm5d_data_show_monitor)
        self.lineEdit_7.setGeometry(QtCore.QRect(250, 90, 81, 25))
        self.lineEdit_7.setReadOnly(True)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.label_18 = QtWidgets.QLabel(arm5d_data_show_monitor)
        self.label_18.setGeometry(QtCore.QRect(220, 50, 30, 17))
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(arm5d_data_show_monitor)
        self.label_19.setGeometry(QtCore.QRect(340, 50, 40, 17))
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(arm5d_data_show_monitor)
        self.label_20.setGeometry(QtCore.QRect(220, 130, 30, 17))
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(arm5d_data_show_monitor)
        self.label_21.setGeometry(QtCore.QRect(340, 170, 40, 17))
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(arm5d_data_show_monitor)
        self.label_22.setGeometry(QtCore.QRect(340, 210, 40, 16))
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(arm5d_data_show_monitor)
        self.label_23.setGeometry(QtCore.QRect(220, 210, 30, 17))
        self.label_23.setObjectName("label_23")
        self.lineEdit_8 = QtWidgets.QLineEdit(arm5d_data_show_monitor)
        self.lineEdit_8.setGeometry(QtCore.QRect(250, 50, 81, 25))
        self.lineEdit_8.setReadOnly(True)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.label_24 = QtWidgets.QLabel(arm5d_data_show_monitor)
        self.label_24.setGeometry(QtCore.QRect(340, 130, 40, 17))
        self.label_24.setObjectName("label_24")
        self.lineEdit_9 = QtWidgets.QLineEdit(arm5d_data_show_monitor)
        self.lineEdit_9.setGeometry(QtCore.QRect(250, 130, 81, 25))
        self.lineEdit_9.setReadOnly(True)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.lineEdit_10 = QtWidgets.QLineEdit(arm5d_data_show_monitor)
        self.lineEdit_10.setGeometry(QtCore.QRect(250, 170, 81, 25))
        self.lineEdit_10.setReadOnly(True)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.label_25 = QtWidgets.QLabel(arm5d_data_show_monitor)
        self.label_25.setGeometry(QtCore.QRect(340, 90, 40, 17))
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(arm5d_data_show_monitor)
        self.label_26.setGeometry(QtCore.QRect(220, 90, 30, 17))
        self.label_26.setObjectName("label_26")
        self.lineEdit_17 = QtWidgets.QLineEdit(arm5d_data_show_monitor)
        self.lineEdit_17.setGeometry(QtCore.QRect(250, 210, 81, 25))
        self.lineEdit_17.setReadOnly(True)
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.lineEdit_11 = QtWidgets.QLineEdit(arm5d_data_show_monitor)
        self.lineEdit_11.setGeometry(QtCore.QRect(250, 10, 81, 25))
        self.lineEdit_11.setReadOnly(True)
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.label_27 = QtWidgets.QLabel(arm5d_data_show_monitor)
        self.label_27.setGeometry(QtCore.QRect(340, 10, 40, 17))
        self.label_27.setObjectName("label_27")

        self.retranslateUi(arm5d_data_show_monitor)
        QtCore.QMetaObject.connectSlotsByName(arm5d_data_show_monitor)

    def retranslateUi(self, arm5d_data_show_monitor):
        _translate = QtCore.QCoreApplication.translate
        arm5d_data_show_monitor.setWindowTitle(_translate("arm5d_data_show_monitor", "示教数据监控"))
        self.label_7.setText(_translate("arm5d_data_show_monitor", "T2"))
        self.label_3.setText(_translate("arm5d_data_show_monitor", "T3"))
        self.label_4.setText(_translate("arm5d_data_show_monitor", "i4"))
        self.label_5.setText(_translate("arm5d_data_show_monitor", "t5"))
        self.label_2.setText(_translate("arm5d_data_show_monitor", "I1"))
        self.label_6.setText(_translate("arm5d_data_show_monitor", "deg"))
        self.label_8.setText(_translate("arm5d_data_show_monitor", "deg"))
        self.label_9.setText(_translate("arm5d_data_show_monitor", "deg"))
        self.label_10.setText(_translate("arm5d_data_show_monitor", "deg"))
        self.label_11.setText(_translate("arm5d_data_show_monitor", "deg"))
        self.label_16.setText(_translate("arm5d_data_show_monitor", "X"))
        self.label_17.setText(_translate("arm5d_data_show_monitor", "RY"))
        self.label_18.setText(_translate("arm5d_data_show_monitor", "Y"))
        self.label_19.setText(_translate("arm5d_data_show_monitor", "mm"))
        self.label_20.setText(_translate("arm5d_data_show_monitor", "RX"))
        self.label_21.setText(_translate("arm5d_data_show_monitor", "deg"))
        self.label_22.setText(_translate("arm5d_data_show_monitor", "deg"))
        self.label_23.setText(_translate("arm5d_data_show_monitor", "RZ"))
        self.label_24.setText(_translate("arm5d_data_show_monitor", "deg"))
        self.label_25.setText(_translate("arm5d_data_show_monitor", "mm"))
        self.label_26.setText(_translate("arm5d_data_show_monitor", "Z"))
        self.label_27.setText(_translate("arm5d_data_show_monitor", "mm"))

