# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'arm5d_descart_control.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_arm5d_descart_control(object):
    def setupUi(self, arm5d_descart_control):
        arm5d_descart_control.setObjectName("arm5d_descart_control")
        arm5d_descart_control.resize(755, 465)
        self.label_23 = QtWidgets.QLabel(arm5d_descart_control)
        self.label_23.setGeometry(QtCore.QRect(420, 120, 40, 16))
        self.label_23.setObjectName("label_23")
        self.pushButton_4 = QtWidgets.QPushButton(arm5d_descart_control)
        self.pushButton_4.setGeometry(QtCore.QRect(50, 110, 60, 25))
        self.pushButton_4.setCheckable(True)
        self.pushButton_4.setObjectName("pushButton_4")
        self.lineEdit_16 = QtWidgets.QLineEdit(arm5d_descart_control)
        self.lineEdit_16.setGeometry(QtCore.QRect(130, 70, 71, 25))
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.label_37 = QtWidgets.QLabel(arm5d_descart_control)
        self.label_37.setGeometry(QtCore.QRect(210, 190, 40, 16))
        self.label_37.setObjectName("label_37")
        self.label_14 = QtWidgets.QLabel(arm5d_descart_control)
        self.label_14.setGeometry(QtCore.QRect(290, 310, 21, 17))
        self.label_14.setObjectName("label_14")
        self.pushButton_1 = QtWidgets.QPushButton(arm5d_descart_control)
        self.pushButton_1.setGeometry(QtCore.QRect(50, 30, 60, 25))
        self.pushButton_1.setCheckable(True)
        self.pushButton_1.setObjectName("pushButton_1")
        self.lineEdit_10 = QtWidgets.QLineEdit(arm5d_descart_control)
        self.lineEdit_10.setGeometry(QtCore.QRect(340, 280, 70, 25))
        self.lineEdit_10.setDragEnabled(True)
        self.lineEdit_10.setReadOnly(True)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.pushButton_2 = QtWidgets.QPushButton(arm5d_descart_control)
        self.pushButton_2.setGeometry(QtCore.QRect(300, 380, 80, 60))
        self.pushButton_2.setStyleSheet("background-color: rgb(204, 0, 0);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_20 = QtWidgets.QLabel(arm5d_descart_control)
        self.label_20.setGeometry(QtCore.QRect(420, 60, 40, 16))
        self.label_20.setObjectName("label_20")
        self.label_17 = QtWidgets.QLabel(arm5d_descart_control)
        self.label_17.setGeometry(QtCore.QRect(480, 0, 67, 17))
        self.label_17.setObjectName("label_17")
        self.label_32 = QtWidgets.QLabel(arm5d_descart_control)
        self.label_32.setGeometry(QtCore.QRect(210, 110, 40, 17))
        self.label_32.setObjectName("label_32")
        self.pushButton = QtWidgets.QPushButton(arm5d_descart_control)
        self.pushButton.setGeometry(QtCore.QRect(0, -10, 41, 25))
        self.pushButton.setObjectName("pushButton")
        self.label_27 = QtWidgets.QLabel(arm5d_descart_control)
        self.label_27.setGeometry(QtCore.QRect(420, 220, 40, 17))
        self.label_27.setObjectName("label_27")
        self.lineEdit_21 = QtWidgets.QLineEdit(arm5d_descart_control)
        self.lineEdit_21.setGeometry(QtCore.QRect(130, 190, 71, 25))
        self.lineEdit_21.setObjectName("lineEdit_21")
        self.lineEdit_20 = QtWidgets.QLineEdit(arm5d_descart_control)
        self.lineEdit_20.setGeometry(QtCore.QRect(130, 150, 71, 25))
        self.lineEdit_20.setObjectName("lineEdit_20")
        self.label_16 = QtWidgets.QLabel(arm5d_descart_control)
        self.label_16.setGeometry(QtCore.QRect(420, 190, 40, 17))
        self.label_16.setObjectName("label_16")
        self.pushButton_15 = QtWidgets.QPushButton(arm5d_descart_control)
        self.pushButton_15.setGeometry(QtCore.QRect(50, 230, 60, 25))
        self.pushButton_15.setCheckable(True)
        self.pushButton_15.setObjectName("pushButton_15")
        self.pushButton_5 = QtWidgets.QPushButton(arm5d_descart_control)
        self.pushButton_5.setGeometry(QtCore.QRect(50, 150, 60, 25))
        self.pushButton_5.setCheckable(True)
        self.pushButton_5.setObjectName("pushButton_5")
        self.lineEdit_2 = QtWidgets.QLineEdit(arm5d_descart_control)
        self.lineEdit_2.setGeometry(QtCore.QRect(340, 30, 70, 25))
        self.lineEdit_2.setDragEnabled(True)
        self.lineEdit_2.setReadOnly(True)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_35 = QtWidgets.QLabel(arm5d_descart_control)
        self.label_35.setGeometry(QtCore.QRect(210, 150, 40, 16))
        self.label_35.setObjectName("label_35")
        self.label_9 = QtWidgets.QLabel(arm5d_descart_control)
        self.label_9.setGeometry(QtCore.QRect(290, 280, 21, 17))
        self.label_9.setObjectName("label_9")
        self.label_8 = QtWidgets.QLabel(arm5d_descart_control)
        self.label_8.setGeometry(QtCore.QRect(130, 340, 31, 17))
        self.label_8.setObjectName("label_8")
        self.lineEdit_18 = QtWidgets.QLineEdit(arm5d_descart_control)
        self.lineEdit_18.setGeometry(QtCore.QRect(130, 110, 71, 25))
        self.lineEdit_18.setObjectName("lineEdit_18")
        self.lineEdit_12 = QtWidgets.QLineEdit(arm5d_descart_control)
        self.lineEdit_12.setGeometry(QtCore.QRect(340, 250, 70, 25))
        self.lineEdit_12.setDragEnabled(True)
        self.lineEdit_12.setReadOnly(True)
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.lineEdit_9 = QtWidgets.QLineEdit(arm5d_descart_control)
        self.lineEdit_9.setGeometry(QtCore.QRect(340, 190, 70, 25))
        self.lineEdit_9.setText("")
        self.lineEdit_9.setDragEnabled(True)
        self.lineEdit_9.setReadOnly(True)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.lineEdit_4 = QtWidgets.QLineEdit(arm5d_descart_control)
        self.lineEdit_4.setGeometry(QtCore.QRect(340, 120, 70, 25))
        self.lineEdit_4.setDragEnabled(True)
        self.lineEdit_4.setReadOnly(True)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_11 = QtWidgets.QLineEdit(arm5d_descart_control)
        self.lineEdit_11.setGeometry(QtCore.QRect(340, 340, 70, 25))
        self.lineEdit_11.setDragEnabled(True)
        self.lineEdit_11.setReadOnly(True)
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.label_15 = QtWidgets.QLabel(arm5d_descart_control)
        self.label_15.setGeometry(QtCore.QRect(290, 190, 21, 17))
        self.label_15.setObjectName("label_15")
        self.label_39 = QtWidgets.QLabel(arm5d_descart_control)
        self.label_39.setGeometry(QtCore.QRect(210, 230, 40, 16))
        self.label_39.setObjectName("label_39")
        self.pushButton_3 = QtWidgets.QPushButton(arm5d_descart_control)
        self.pushButton_3.setGeometry(QtCore.QRect(50, 70, 60, 25))
        self.pushButton_3.setCheckable(True)
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_30 = QtWidgets.QLabel(arm5d_descart_control)
        self.label_30.setGeometry(QtCore.QRect(210, 30, 40, 17))
        self.label_30.setObjectName("label_30")
        self.label_21 = QtWidgets.QLabel(arm5d_descart_control)
        self.label_21.setGeometry(QtCore.QRect(420, 90, 40, 16))
        self.label_21.setObjectName("label_21")
        self.label_11 = QtWidgets.QLabel(arm5d_descart_control)
        self.label_11.setGeometry(QtCore.QRect(290, 340, 21, 17))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(arm5d_descart_control)
        self.label_12.setGeometry(QtCore.QRect(290, 220, 21, 17))
        self.label_12.setObjectName("label_12")
        self.listWidget = QtWidgets.QListWidget(arm5d_descart_control)
        self.listWidget.setGeometry(QtCore.QRect(480, 20, 256, 421))
        self.listWidget.setObjectName("listWidget")
        self.label_22 = QtWidgets.QLabel(arm5d_descart_control)
        self.label_22.setGeometry(QtCore.QRect(420, 150, 40, 16))
        self.label_22.setObjectName("label_22")
        self.label_24 = QtWidgets.QLabel(arm5d_descart_control)
        self.label_24.setGeometry(QtCore.QRect(420, 280, 40, 16))
        self.label_24.setObjectName("label_24")
        self.lineEdit_14 = QtWidgets.QLineEdit(arm5d_descart_control)
        self.lineEdit_14.setGeometry(QtCore.QRect(130, 30, 71, 25))
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.lineEdit_5 = QtWidgets.QLineEdit(arm5d_descart_control)
        self.lineEdit_5.setGeometry(QtCore.QRect(340, 90, 70, 25))
        self.lineEdit_5.setDragEnabled(True)
        self.lineEdit_5.setReadOnly(True)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.pushButton_6 = QtWidgets.QPushButton(arm5d_descart_control)
        self.pushButton_6.setGeometry(QtCore.QRect(50, 190, 60, 25))
        self.pushButton_6.setCheckable(True)
        self.pushButton_6.setObjectName("pushButton_6")
        self.lineEdit_6 = QtWidgets.QLineEdit(arm5d_descart_control)
        self.lineEdit_6.setGeometry(QtCore.QRect(340, 150, 70, 25))
        self.lineEdit_6.setDragEnabled(True)
        self.lineEdit_6.setReadOnly(True)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.label_25 = QtWidgets.QLabel(arm5d_descart_control)
        self.label_25.setGeometry(QtCore.QRect(420, 310, 40, 16))
        self.label_25.setObjectName("label_25")
        self.lineEdit_13 = QtWidgets.QLineEdit(arm5d_descart_control)
        self.lineEdit_13.setGeometry(QtCore.QRect(340, 220, 70, 25))
        self.lineEdit_13.setDragEnabled(True)
        self.lineEdit_13.setReadOnly(True)
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.lineEdit_8 = QtWidgets.QLineEdit(arm5d_descart_control)
        self.lineEdit_8.setGeometry(QtCore.QRect(340, 310, 70, 25))
        self.lineEdit_8.setDragEnabled(True)
        self.lineEdit_8.setReadOnly(True)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.label_26 = QtWidgets.QLabel(arm5d_descart_control)
        self.label_26.setGeometry(QtCore.QRect(420, 340, 40, 16))
        self.label_26.setObjectName("label_26")
        self.label_28 = QtWidgets.QLabel(arm5d_descart_control)
        self.label_28.setGeometry(QtCore.QRect(420, 250, 40, 17))
        self.label_28.setObjectName("label_28")
        self.pushButton_7 = QtWidgets.QPushButton(arm5d_descart_control)
        self.pushButton_7.setGeometry(QtCore.QRect(100, 380, 89, 61))
        self.pushButton_7.setObjectName("pushButton_7")
        self.lineEdit_3 = QtWidgets.QLineEdit(arm5d_descart_control)
        self.lineEdit_3.setGeometry(QtCore.QRect(340, 60, 70, 25))
        self.lineEdit_3.setDragEnabled(True)
        self.lineEdit_3.setReadOnly(True)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_31 = QtWidgets.QLabel(arm5d_descart_control)
        self.label_31.setGeometry(QtCore.QRect(210, 70, 40, 17))
        self.label_31.setObjectName("label_31")
        self.lineEdit_23 = QtWidgets.QLineEdit(arm5d_descart_control)
        self.lineEdit_23.setGeometry(QtCore.QRect(130, 230, 71, 25))
        self.lineEdit_23.setObjectName("lineEdit_23")
        self.label_19 = QtWidgets.QLabel(arm5d_descart_control)
        self.label_19.setGeometry(QtCore.QRect(420, 30, 40, 16))
        self.label_19.setObjectName("label_19")
        self.label_13 = QtWidgets.QLabel(arm5d_descart_control)
        self.label_13.setGeometry(QtCore.QRect(290, 250, 21, 17))
        self.label_13.setObjectName("label_13")
        self.label_3 = QtWidgets.QLabel(arm5d_descart_control)
        self.label_3.setGeometry(QtCore.QRect(290, 60, 31, 17))
        self.label_3.setObjectName("label_3")
        self.label_2 = QtWidgets.QLabel(arm5d_descart_control)
        self.label_2.setGeometry(QtCore.QRect(290, 90, 31, 17))
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(arm5d_descart_control)
        self.label_4.setGeometry(QtCore.QRect(290, 120, 31, 17))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(arm5d_descart_control)
        self.label_5.setGeometry(QtCore.QRect(290, 150, 31, 17))
        self.label_5.setObjectName("label_5")
        self.label = QtWidgets.QLabel(arm5d_descart_control)
        self.label.setGeometry(QtCore.QRect(290, 30, 31, 17))
        self.label.setObjectName("label")
        self.horizontalSlider = QtWidgets.QSlider(arm5d_descart_control)
        self.horizontalSlider.setGeometry(QtCore.QRect(80, 310, 121, 16))
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")

        self.retranslateUi(arm5d_descart_control)
        self.pushButton_1.clicked.connect(arm5d_descart_control.X_data)
        self.pushButton_3.clicked.connect(arm5d_descart_control.Y_data)
        self.pushButton_4.clicked.connect(arm5d_descart_control.Z_data)
        self.pushButton_5.clicked.connect(arm5d_descart_control.RX_data)
        self.pushButton_6.clicked.connect(arm5d_descart_control.RY_data)
        self.pushButton_15.clicked.connect(arm5d_descart_control.RZ_data)
        self.horizontalSlider.valueChanged['int'].connect(arm5d_descart_control.change_velocity)
        self.pushButton_7.clicked.connect(arm5d_descart_control.teach_record)
        self.pushButton_2.clicked.connect(arm5d_descart_control.quick_stop)
        self.pushButton.clicked.connect(arm5d_descart_control.return_last_ui)
        QtCore.QMetaObject.connectSlotsByName(arm5d_descart_control)

    def retranslateUi(self, arm5d_descart_control):
        _translate = QtCore.QCoreApplication.translate
        arm5d_descart_control.setWindowTitle(_translate("arm5d_descart_control", "笛卡尔空间控制"))
        self.label_23.setText(_translate("arm5d_descart_control", "deg"))
        self.pushButton_4.setText(_translate("arm5d_descart_control", "Z"))
        self.label_37.setText(_translate("arm5d_descart_control", "deg"))
        self.label_14.setText(_translate("arm5d_descart_control", "RY"))
        self.pushButton_1.setText(_translate("arm5d_descart_control", "X"))
        self.pushButton_2.setText(_translate("arm5d_descart_control", "急停"))
        self.label_20.setText(_translate("arm5d_descart_control", "deg"))
        self.label_17.setText(_translate("arm5d_descart_control", "执行过程"))
        self.label_32.setText(_translate("arm5d_descart_control", "mm"))
        self.pushButton.setText(_translate("arm5d_descart_control", "返回"))
        self.label_27.setText(_translate("arm5d_descart_control", "mm"))
        self.label_16.setText(_translate("arm5d_descart_control", "mm"))
        self.pushButton_15.setText(_translate("arm5d_descart_control", "RZ"))
        self.pushButton_5.setText(_translate("arm5d_descart_control", "RX"))
        self.label_35.setText(_translate("arm5d_descart_control", "deg"))
        self.label_9.setText(_translate("arm5d_descart_control", "RX"))
        self.label_8.setText(_translate("arm5d_descart_control", "速度"))
        self.label_15.setText(_translate("arm5d_descart_control", "X"))
        self.label_39.setText(_translate("arm5d_descart_control", "deg"))
        self.pushButton_3.setText(_translate("arm5d_descart_control", "Y"))
        self.label_30.setText(_translate("arm5d_descart_control", "mm"))
        self.label_21.setText(_translate("arm5d_descart_control", "deg"))
        self.label_11.setText(_translate("arm5d_descart_control", "RZ"))
        self.label_12.setText(_translate("arm5d_descart_control", "Y"))
        self.label_22.setText(_translate("arm5d_descart_control", "deg"))
        self.label_24.setText(_translate("arm5d_descart_control", "deg"))
        self.pushButton_6.setText(_translate("arm5d_descart_control", "RY"))
        self.label_25.setText(_translate("arm5d_descart_control", "deg"))
        self.label_26.setText(_translate("arm5d_descart_control", "deg"))
        self.label_28.setText(_translate("arm5d_descart_control", "mm"))
        self.pushButton_7.setText(_translate("arm5d_descart_control", "示教记录"))
        self.label_31.setText(_translate("arm5d_descart_control", "mm"))
        self.label_19.setText(_translate("arm5d_descart_control", "deg"))
        self.label_13.setText(_translate("arm5d_descart_control", "Z"))
        self.label_3.setText(_translate("arm5d_descart_control", "T2"))
        self.label_2.setText(_translate("arm5d_descart_control", "T3"))
        self.label_4.setText(_translate("arm5d_descart_control", "i4"))
        self.label_5.setText(_translate("arm5d_descart_control", "t5"))
        self.label.setText(_translate("arm5d_descart_control", "I1"))

