# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'arm5d_joint_control.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_arm5d_joint_control(object):
    def setupUi(self, arm5d_joint_control):
        arm5d_joint_control.setObjectName("arm5d_joint_control")
        arm5d_joint_control.resize(726, 429)
        self.label_12 = QtWidgets.QLabel(arm5d_joint_control)
        self.label_12.setGeometry(QtCore.QRect(400, 40, 30, 17))
        self.label_12.setObjectName("label_12")
        self.pushButton_8 = QtWidgets.QPushButton(arm5d_joint_control)
        self.pushButton_8.setGeometry(QtCore.QRect(190, 200, 60, 50))
        self.pushButton_8.setCheckable(True)
        self.pushButton_8.setObjectName("pushButton_8")
        self.lineEdit_3 = QtWidgets.QLineEdit(arm5d_joint_control)
        self.lineEdit_3.setGeometry(QtCore.QRect(320, 70, 70, 25))
        self.lineEdit_3.setDragEnabled(True)
        self.lineEdit_3.setReadOnly(True)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_9 = QtWidgets.QLabel(arm5d_joint_control)
        self.label_9.setGeometry(QtCore.QRect(40, 230, 41, 20))
        self.label_9.setObjectName("label_9")
        self.label_2 = QtWidgets.QLabel(arm5d_joint_control)
        self.label_2.setGeometry(QtCore.QRect(290, 100, 31, 17))
        self.label_2.setObjectName("label_2")
        self.listWidget = QtWidgets.QListWidget(arm5d_joint_control)
        self.listWidget.setGeometry(QtCore.QRect(450, 40, 256, 371))
        self.listWidget.setObjectName("listWidget")
        self.pushButton_6 = QtWidgets.QPushButton(arm5d_joint_control)
        self.pushButton_6.setGeometry(QtCore.QRect(100, 360, 60, 50))
        self.pushButton_6.setCheckable(True)
        self.pushButton_6.setObjectName("pushButton_6")
        self.label = QtWidgets.QLabel(arm5d_joint_control)
        self.label.setGeometry(QtCore.QRect(290, 40, 31, 17))
        self.label.setObjectName("label")
        self.pushButton_5 = QtWidgets.QPushButton(arm5d_joint_control)
        self.pushButton_5.setGeometry(QtCore.QRect(100, 280, 60, 50))
        self.pushButton_5.setCheckable(True)
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalSlider = QtWidgets.QSlider(arm5d_joint_control)
        self.verticalSlider.setGeometry(QtCore.QRect(40, 70, 16, 160))
        self.verticalSlider.setMaximum(100)
        self.verticalSlider.setSingleStep(100)
        self.verticalSlider.setProperty("value", 20)
        self.verticalSlider.setTracking(True)
        self.verticalSlider.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider.setInvertedAppearance(False)
        self.verticalSlider.setInvertedControls(False)
        self.verticalSlider.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.verticalSlider.setTickInterval(10)
        self.verticalSlider.setObjectName("verticalSlider")
        self.pushButton_1 = QtWidgets.QPushButton(arm5d_joint_control)
        self.pushButton_1.setGeometry(QtCore.QRect(100, 40, 60, 50))
        self.pushButton_1.setCheckable(True)
        self.pushButton_1.setObjectName("pushButton_1")
        self.lineEdit_4 = QtWidgets.QLineEdit(arm5d_joint_control)
        self.lineEdit_4.setGeometry(QtCore.QRect(320, 130, 70, 25))
        self.lineEdit_4.setDragEnabled(True)
        self.lineEdit_4.setReadOnly(True)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.pushButton_16 = QtWidgets.QPushButton(arm5d_joint_control)
        self.pushButton_16.setGeometry(QtCore.QRect(310, 280, 89, 51))
        self.pushButton_16.setObjectName("pushButton_16")
        self.label_5 = QtWidgets.QLabel(arm5d_joint_control)
        self.label_5.setGeometry(QtCore.QRect(290, 160, 31, 17))
        self.label_5.setObjectName("label_5")
        self.pushButton_9 = QtWidgets.QPushButton(arm5d_joint_control)
        self.pushButton_9.setGeometry(QtCore.QRect(190, 280, 60, 50))
        self.pushButton_9.setCheckable(True)
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton = QtWidgets.QPushButton(arm5d_joint_control)
        self.pushButton.setGeometry(QtCore.QRect(0, 0, 51, 25))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_10 = QtWidgets.QPushButton(arm5d_joint_control)
        self.pushButton_10.setGeometry(QtCore.QRect(190, 360, 61, 51))
        self.pushButton_10.setCheckable(True)
        self.pushButton_10.setObjectName("pushButton_10")
        self.label_14 = QtWidgets.QLabel(arm5d_joint_control)
        self.label_14.setGeometry(QtCore.QRect(400, 100, 30, 17))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(arm5d_joint_control)
        self.label_15.setGeometry(QtCore.QRect(400, 130, 30, 17))
        self.label_15.setObjectName("label_15")
        self.lineEdit_2 = QtWidgets.QLineEdit(arm5d_joint_control)
        self.lineEdit_2.setGeometry(QtCore.QRect(320, 40, 70, 25))
        self.lineEdit_2.setDragEnabled(True)
        self.lineEdit_2.setReadOnly(True)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton_4 = QtWidgets.QPushButton(arm5d_joint_control)
        self.pushButton_4.setGeometry(QtCore.QRect(100, 200, 60, 50))
        self.pushButton_4.setCheckable(True)
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_2 = QtWidgets.QPushButton(arm5d_joint_control)
        self.pushButton_2.setGeometry(QtCore.QRect(190, 40, 60, 50))
        self.pushButton_2.setCheckable(True)
        self.pushButton_2.setObjectName("pushButton_2")
        self.lineEdit_5 = QtWidgets.QLineEdit(arm5d_joint_control)
        self.lineEdit_5.setGeometry(QtCore.QRect(320, 100, 70, 25))
        self.lineEdit_5.setDragEnabled(True)
        self.lineEdit_5.setReadOnly(True)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.label_10 = QtWidgets.QLabel(arm5d_joint_control)
        self.label_10.setGeometry(QtCore.QRect(450, 10, 67, 17))
        self.label_10.setObjectName("label_10")
        self.label_8 = QtWidgets.QLabel(arm5d_joint_control)
        self.label_8.setGeometry(QtCore.QRect(400, 160, 30, 17))
        self.label_8.setObjectName("label_8")
        self.pushButton_7 = QtWidgets.QPushButton(arm5d_joint_control)
        self.pushButton_7.setGeometry(QtCore.QRect(190, 120, 60, 50))
        self.pushButton_7.setCheckable(True)
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_3 = QtWidgets.QPushButton(arm5d_joint_control)
        self.pushButton_3.setGeometry(QtCore.QRect(100, 120, 60, 50))
        self.pushButton_3.setCheckable(True)
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_4 = QtWidgets.QLabel(arm5d_joint_control)
        self.label_4.setGeometry(QtCore.QRect(290, 130, 31, 17))
        self.label_4.setObjectName("label_4")
        self.label_3 = QtWidgets.QLabel(arm5d_joint_control)
        self.label_3.setGeometry(QtCore.QRect(290, 70, 31, 17))
        self.label_3.setObjectName("label_3")
        self.lineEdit_6 = QtWidgets.QLineEdit(arm5d_joint_control)
        self.lineEdit_6.setGeometry(QtCore.QRect(320, 160, 70, 25))
        self.lineEdit_6.setDragEnabled(True)
        self.lineEdit_6.setReadOnly(True)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.pushButton_15 = QtWidgets.QPushButton(arm5d_joint_control)
        self.pushButton_15.setGeometry(QtCore.QRect(310, 200, 89, 51))
        self.pushButton_15.setObjectName("pushButton_15")
        self.label_13 = QtWidgets.QLabel(arm5d_joint_control)
        self.label_13.setGeometry(QtCore.QRect(400, 70, 30, 17))
        self.label_13.setObjectName("label_13")
        self.pushButton_17 = QtWidgets.QPushButton(arm5d_joint_control)
        self.pushButton_17.setGeometry(QtCore.QRect(310, 360, 89, 51))
        self.pushButton_17.setStyleSheet("background-color: rgb(204, 0, 0);")
        self.pushButton_17.setObjectName("pushButton_17")


        self.retranslateUi(arm5d_joint_control)
        self.pushButton_1.clicked['bool'].connect(arm5d_joint_control.I1_add_position)
        self.pushButton_2.clicked['bool'].connect(arm5d_joint_control.I1_sub_position)
        self.pushButton_3.clicked['bool'].connect(arm5d_joint_control.T2_add_position)
        self.pushButton_7.clicked['bool'].connect(arm5d_joint_control.T2_sub_position)
        self.pushButton_4.clicked['bool'].connect(arm5d_joint_control.T3_add_position)
        self.pushButton_8.clicked['bool'].connect(arm5d_joint_control.T3_sub_position)
        self.pushButton_5.clicked['bool'].connect(arm5d_joint_control.i4_add_position)
        self.pushButton_9.clicked['bool'].connect(arm5d_joint_control.i4_sub_position)
        self.pushButton_6.clicked['bool'].connect(arm5d_joint_control.t5_add_position)
        self.pushButton_10.clicked['bool'].connect(arm5d_joint_control.t5_sub_position)
        self.pushButton_15.clicked.connect(arm5d_joint_control.set_zero)
        self.pushButton_16.clicked.connect(arm5d_joint_control.return_zero)
        self.pushButton_17.clicked.connect(arm5d_joint_control.quick_stop)
        self.pushButton.clicked.connect(arm5d_joint_control.return_last_ui)
        QtCore.QMetaObject.connectSlotsByName(arm5d_joint_control)

    def retranslateUi(self, arm5d_joint_control):
        _translate = QtCore.QCoreApplication.translate
        arm5d_joint_control.setWindowTitle(_translate("arm5d_joint_control", "关节空间控制"))
        self.label_12.setText(_translate("arm5d_joint_control", "deg"))
        self.pushButton_8.setText(_translate("arm5d_joint_control", "T3(-)"))
        self.label_9.setText(_translate("arm5d_joint_control", "速度"))
        self.label_2.setText(_translate("arm5d_joint_control", "T3"))
        self.pushButton_6.setText(_translate("arm5d_joint_control", "t5(+)"))
        self.label.setText(_translate("arm5d_joint_control", "I1"))
        self.pushButton_5.setText(_translate("arm5d_joint_control", "i4(+)"))
        self.pushButton_1.setText(_translate("arm5d_joint_control", "I1(+)"))
        self.pushButton_16.setText(_translate("arm5d_joint_control", "回零"))
        self.label_5.setText(_translate("arm5d_joint_control", "t5"))
        self.pushButton_9.setText(_translate("arm5d_joint_control", "i4(-)"))
        self.pushButton.setText(_translate("arm5d_joint_control", "返回"))
        self.pushButton_10.setText(_translate("arm5d_joint_control", "t5(-)"))
        self.label_14.setText(_translate("arm5d_joint_control", "deg"))
        self.label_15.setText(_translate("arm5d_joint_control", "deg"))
        self.pushButton_4.setText(_translate("arm5d_joint_control", "T3(+)"))
        self.pushButton_2.setText(_translate("arm5d_joint_control", "I1(-)"))
        self.label_10.setText(_translate("arm5d_joint_control", "执行过程"))
        self.label_8.setText(_translate("arm5d_joint_control", "deg"))
        self.pushButton_7.setText(_translate("arm5d_joint_control", "T2(-)"))
        self.pushButton_3.setText(_translate("arm5d_joint_control", "T2(+)"))
        self.label_4.setText(_translate("arm5d_joint_control", "i4"))
        self.label_3.setText(_translate("arm5d_joint_control", "T2"))
        self.pushButton_15.setText(_translate("arm5d_joint_control", "设置零位"))
        self.label_13.setText(_translate("arm5d_joint_control", "deg"))
        self.pushButton_17.setText(_translate("arm5d_joint_control", "急停"))

