# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'wheel_bipedal_7d.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_wheel_bipedal_7d(object):
    def setupUi(self, wheel_bipedal_7d):
        wheel_bipedal_7d.setObjectName("wheel_bipedal_7d")
        wheel_bipedal_7d.resize(430, 542)
        self.pushButton_16 = QtWidgets.QPushButton(wheel_bipedal_7d)
        self.pushButton_16.setGeometry(QtCore.QRect(200, 470, 89, 51))
        self.pushButton_16.setObjectName("pushButton_16")
        self.label = QtWidgets.QLabel(wheel_bipedal_7d)
        self.label.setGeometry(QtCore.QRect(230, 30, 16, 17))
        self.label.setObjectName("label")
        self.pushButton_15 = QtWidgets.QPushButton(wheel_bipedal_7d)
        self.pushButton_15.setGeometry(QtCore.QRect(310, 470, 89, 51))
        self.pushButton_15.setObjectName("pushButton_15")
        self.pushButton_8 = QtWidgets.QPushButton(wheel_bipedal_7d)
        self.pushButton_8.setGeometry(QtCore.QRect(110, 190, 60, 50))
        self.pushButton_8.setCheckable(True)
        self.pushButton_8.setObjectName("pushButton_8")
        self.label_12 = QtWidgets.QLabel(wheel_bipedal_7d)
        self.label_12.setGeometry(QtCore.QRect(350, 30, 30, 17))
        self.label_12.setObjectName("label_12")
        self.pushButton_1 = QtWidgets.QPushButton(wheel_bipedal_7d)
        self.pushButton_1.setGeometry(QtCore.QRect(20, 50, 60, 50))
        self.pushButton_1.setCheckable(True)
        self.pushButton_1.setObjectName("pushButton_1")
        self.lineEdit_2 = QtWidgets.QLineEdit(wheel_bipedal_7d)
        self.lineEdit_2.setGeometry(QtCore.QRect(260, 30, 70, 25))
        self.lineEdit_2.setDragEnabled(True)
        self.lineEdit_2.setReadOnly(True)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton_2 = QtWidgets.QPushButton(wheel_bipedal_7d)
        self.pushButton_2.setGeometry(QtCore.QRect(110, 50, 60, 50))
        self.pushButton_2.setCheckable(True)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_10 = QtWidgets.QPushButton(wheel_bipedal_7d)
        self.pushButton_10.setGeometry(QtCore.QRect(110, 330, 60, 50))
        self.pushButton_10.setCheckable(True)
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_7 = QtWidgets.QPushButton(wheel_bipedal_7d)
        self.pushButton_7.setGeometry(QtCore.QRect(110, 120, 60, 50))
        self.pushButton_7.setCheckable(True)
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton = QtWidgets.QPushButton(wheel_bipedal_7d)
        self.pushButton.setGeometry(QtCore.QRect(0, 0, 51, 25))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_6 = QtWidgets.QPushButton(wheel_bipedal_7d)
        self.pushButton_6.setGeometry(QtCore.QRect(20, 330, 60, 50))
        self.pushButton_6.setCheckable(True)
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_3 = QtWidgets.QPushButton(wheel_bipedal_7d)
        self.pushButton_3.setGeometry(QtCore.QRect(20, 120, 60, 50))
        self.pushButton_3.setCheckable(True)
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(wheel_bipedal_7d)
        self.pushButton_4.setGeometry(QtCore.QRect(20, 190, 60, 50))
        self.pushButton_4.setCheckable(True)
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_9 = QtWidgets.QPushButton(wheel_bipedal_7d)
        self.pushButton_9.setGeometry(QtCore.QRect(110, 260, 60, 50))
        self.pushButton_9.setCheckable(True)
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_5 = QtWidgets.QPushButton(wheel_bipedal_7d)
        self.pushButton_5.setGeometry(QtCore.QRect(20, 260, 60, 50))
        self.pushButton_5.setCheckable(True)
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_11 = QtWidgets.QPushButton(wheel_bipedal_7d)
        self.pushButton_11.setGeometry(QtCore.QRect(20, 400, 60, 50))
        self.pushButton_11.setCheckable(True)
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_12 = QtWidgets.QPushButton(wheel_bipedal_7d)
        self.pushButton_12.setGeometry(QtCore.QRect(110, 400, 60, 50))
        self.pushButton_12.setCheckable(True)
        self.pushButton_12.setObjectName("pushButton_12")
        self.pushButton_13 = QtWidgets.QPushButton(wheel_bipedal_7d)
        self.pushButton_13.setGeometry(QtCore.QRect(20, 470, 60, 50))
        self.pushButton_13.setCheckable(True)
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_14 = QtWidgets.QPushButton(wheel_bipedal_7d)
        self.pushButton_14.setGeometry(QtCore.QRect(110, 470, 60, 50))
        self.pushButton_14.setCheckable(True)
        self.pushButton_14.setObjectName("pushButton_14")
        self.label_2 = QtWidgets.QLabel(wheel_bipedal_7d)
        self.label_2.setGeometry(QtCore.QRect(230, 70, 16, 17))
        self.label_2.setObjectName("label_2")
        self.label_13 = QtWidgets.QLabel(wheel_bipedal_7d)
        self.label_13.setGeometry(QtCore.QRect(350, 70, 30, 17))
        self.label_13.setObjectName("label_13")
        self.lineEdit_3 = QtWidgets.QLineEdit(wheel_bipedal_7d)
        self.lineEdit_3.setGeometry(QtCore.QRect(260, 70, 70, 25))
        self.lineEdit_3.setDragEnabled(True)
        self.lineEdit_3.setReadOnly(True)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_3 = QtWidgets.QLabel(wheel_bipedal_7d)
        self.label_3.setGeometry(QtCore.QRect(230, 110, 16, 17))
        self.label_3.setObjectName("label_3")
        self.label_14 = QtWidgets.QLabel(wheel_bipedal_7d)
        self.label_14.setGeometry(QtCore.QRect(350, 110, 30, 17))
        self.label_14.setObjectName("label_14")
        self.lineEdit_4 = QtWidgets.QLineEdit(wheel_bipedal_7d)
        self.lineEdit_4.setGeometry(QtCore.QRect(260, 110, 70, 25))
        self.lineEdit_4.setDragEnabled(True)
        self.lineEdit_4.setReadOnly(True)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_4 = QtWidgets.QLabel(wheel_bipedal_7d)
        self.label_4.setGeometry(QtCore.QRect(230, 150, 16, 17))
        self.label_4.setObjectName("label_4")
        self.label_15 = QtWidgets.QLabel(wheel_bipedal_7d)
        self.label_15.setGeometry(QtCore.QRect(350, 150, 30, 17))
        self.label_15.setObjectName("label_15")
        self.lineEdit_5 = QtWidgets.QLineEdit(wheel_bipedal_7d)
        self.lineEdit_5.setGeometry(QtCore.QRect(260, 150, 70, 25))
        self.lineEdit_5.setDragEnabled(True)
        self.lineEdit_5.setReadOnly(True)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.label_5 = QtWidgets.QLabel(wheel_bipedal_7d)
        self.label_5.setGeometry(QtCore.QRect(230, 190, 16, 17))
        self.label_5.setObjectName("label_5")
        self.label_16 = QtWidgets.QLabel(wheel_bipedal_7d)
        self.label_16.setGeometry(QtCore.QRect(350, 190, 30, 17))
        self.label_16.setObjectName("label_16")
        self.lineEdit_6 = QtWidgets.QLineEdit(wheel_bipedal_7d)
        self.lineEdit_6.setGeometry(QtCore.QRect(260, 190, 70, 25))
        self.lineEdit_6.setDragEnabled(True)
        self.lineEdit_6.setReadOnly(True)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.label_6 = QtWidgets.QLabel(wheel_bipedal_7d)
        self.label_6.setGeometry(QtCore.QRect(230, 230, 16, 17))
        self.label_6.setObjectName("label_6")
        self.label_17 = QtWidgets.QLabel(wheel_bipedal_7d)
        self.label_17.setGeometry(QtCore.QRect(350, 230, 30, 17))
        self.label_17.setObjectName("label_17")
        self.lineEdit_7 = QtWidgets.QLineEdit(wheel_bipedal_7d)
        self.lineEdit_7.setGeometry(QtCore.QRect(260, 230, 70, 25))
        self.lineEdit_7.setDragEnabled(True)
        self.lineEdit_7.setReadOnly(True)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.label_7 = QtWidgets.QLabel(wheel_bipedal_7d)
        self.label_7.setGeometry(QtCore.QRect(230, 280, 16, 17))
        self.label_7.setObjectName("label_7")
        self.label_18 = QtWidgets.QLabel(wheel_bipedal_7d)
        self.label_18.setGeometry(QtCore.QRect(350, 280, 30, 17))
        self.label_18.setObjectName("label_18")
        self.lineEdit_8 = QtWidgets.QLineEdit(wheel_bipedal_7d)
        self.lineEdit_8.setGeometry(QtCore.QRect(260, 280, 70, 25))
        self.lineEdit_8.setDragEnabled(True)
        self.lineEdit_8.setReadOnly(True)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.horizontalSlider = QtWidgets.QSlider(wheel_bipedal_7d)
        self.horizontalSlider.setGeometry(QtCore.QRect(220, 320, 160, 31))
        self.horizontalSlider.setMaximum(1000)
        self.horizontalSlider.setSingleStep(100)
        self.horizontalSlider.setProperty("value", 20)
        self.horizontalSlider.setTracking(True)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setInvertedAppearance(False)
        self.horizontalSlider.setInvertedControls(False)
        self.horizontalSlider.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.horizontalSlider.setTickInterval(100)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.label_8 = QtWidgets.QLabel(wheel_bipedal_7d)
        self.label_8.setGeometry(QtCore.QRect(280, 350, 31, 16))
        self.label_8.setObjectName("label_8")
        self.pushButton_17 = QtWidgets.QPushButton(wheel_bipedal_7d)
        self.pushButton_17.setGeometry(QtCore.QRect(250, 390, 89, 51))
        self.pushButton_17.setObjectName("pushButton_17")
        self.pushButton_17.setStyleSheet("background-color: rgb(239, 41, 41);")
        self.retranslateUi(wheel_bipedal_7d)
        self.pushButton_1.clicked['bool'].connect(wheel_bipedal_7d.I1_add)
        self.pushButton_2.clicked['bool'].connect(wheel_bipedal_7d.I1_sub)
        self.pushButton_3.clicked['bool'].connect(wheel_bipedal_7d.T2_add)
        self.pushButton_7.clicked['bool'].connect(wheel_bipedal_7d.T2_sub)
        self.pushButton_4.clicked['bool'].connect(wheel_bipedal_7d.T3_add)
        self.pushButton_8.clicked['bool'].connect(wheel_bipedal_7d.T3_sub)
        self.pushButton_5.clicked['bool'].connect(wheel_bipedal_7d.I4_add)
        self.pushButton_9.clicked['bool'].connect(wheel_bipedal_7d.I4_sub)
        self.pushButton_6.clicked['bool'].connect(wheel_bipedal_7d.T5_add)
        self.pushButton_10.clicked['bool'].connect(wheel_bipedal_7d.T5_sub)
        self.pushButton_11.clicked['bool'].connect(wheel_bipedal_7d.T6_add)
        self.pushButton_12.clicked['bool'].connect(wheel_bipedal_7d.T6_sub)
        self.pushButton_13.clicked['bool'].connect(wheel_bipedal_7d.I7_add)
        self.pushButton_14.clicked['bool'].connect(wheel_bipedal_7d.I7_sub)
        self.pushButton_16.clicked['bool'].connect(wheel_bipedal_7d.return_zero)
        self.pushButton_15.clicked['bool'].connect(wheel_bipedal_7d.set_zero)
        self.pushButton.clicked['bool'].connect(wheel_bipedal_7d.return_last_ui)
        self.horizontalSlider.valueChanged['int'].connect(wheel_bipedal_7d.change_velocity)
        self.pushButton_17.clicked.connect(wheel_bipedal_7d.quick_stop)
        QtCore.QMetaObject.connectSlotsByName(wheel_bipedal_7d)



    def retranslateUi(self, wheel_bipedal_7d):
        _translate = QtCore.QCoreApplication.translate
        wheel_bipedal_7d.setWindowTitle(_translate("wheel_bipedal_7d", "关节空间控制"))
        self.pushButton_16.setText(_translate("wheel_bipedal_7d", "回零"))
        self.label.setText(_translate("wheel_bipedal_7d", "I1"))
        self.pushButton_15.setText(_translate("wheel_bipedal_7d", "设置零位"))
        self.pushButton_8.setText(_translate("wheel_bipedal_7d", "T3(-)"))
        self.label_12.setText(_translate("wheel_bipedal_7d", "deg"))
        self.pushButton_1.setText(_translate("wheel_bipedal_7d", "I1(+)"))
        self.pushButton_2.setText(_translate("wheel_bipedal_7d", "I1(-)"))
        self.pushButton_10.setText(_translate("wheel_bipedal_7d", "T5(-)"))
        self.pushButton_7.setText(_translate("wheel_bipedal_7d", "T2(-)"))
        self.pushButton.setText(_translate("wheel_bipedal_7d", "返回"))
        self.pushButton_6.setText(_translate("wheel_bipedal_7d", "T5(+)"))
        self.pushButton_3.setText(_translate("wheel_bipedal_7d", "T2(+)"))
        self.pushButton_4.setText(_translate("wheel_bipedal_7d", "T3(+)"))
        self.pushButton_9.setText(_translate("wheel_bipedal_7d", "I4(-)"))
        self.pushButton_5.setText(_translate("wheel_bipedal_7d", "I4(+)"))
        self.pushButton_11.setText(_translate("wheel_bipedal_7d", "T6(+)"))
        self.pushButton_12.setText(_translate("wheel_bipedal_7d", "T6(-)"))
        self.pushButton_13.setText(_translate("wheel_bipedal_7d", "I7(+)"))
        self.pushButton_14.setText(_translate("wheel_bipedal_7d", "I7(-)"))
        self.label_2.setText(_translate("wheel_bipedal_7d", "T2"))
        self.label_13.setText(_translate("wheel_bipedal_7d", "deg"))
        self.label_3.setText(_translate("wheel_bipedal_7d", "T3"))
        self.label_14.setText(_translate("wheel_bipedal_7d", "deg"))
        self.label_4.setText(_translate("wheel_bipedal_7d", "I4"))
        self.label_15.setText(_translate("wheel_bipedal_7d", "deg"))
        self.label_5.setText(_translate("wheel_bipedal_7d", "T5"))
        self.label_16.setText(_translate("wheel_bipedal_7d", "deg"))
        self.label_6.setText(_translate("wheel_bipedal_7d", "T6"))
        self.label_17.setText(_translate("wheel_bipedal_7d", "deg"))
        self.label_7.setText(_translate("wheel_bipedal_7d", "I7"))
        self.label_18.setText(_translate("wheel_bipedal_7d", "deg"))
        self.label_8.setText(_translate("wheel_bipedal_7d", "速度"))
        self.pushButton_17.setText(_translate("wheel_bipedal_7d", "急停"))

