# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'wheel_bipedal7d_data_monitor.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_wheel_bipedal7d_data_monitor(object):
    def setupUi(self, wheel_bipedal7d_data_monitor):
        wheel_bipedal7d_data_monitor.setObjectName("wheel_bipedal7d_data_monitor")
        wheel_bipedal7d_data_monitor.resize(151, 279)
        self.form = wheel_bipedal7d_data_monitor
        self.label_9 = QtWidgets.QLabel(wheel_bipedal7d_data_monitor)
        self.label_9.setGeometry(QtCore.QRect(110, 80, 40, 17))
        self.label_9.setObjectName("label_9")
        self.label_7 = QtWidgets.QLabel(wheel_bipedal7d_data_monitor)
        self.label_7.setGeometry(QtCore.QRect(10, 40, 30, 17))
        self.label_7.setObjectName("label_7")
        self.lineEdit_6 = QtWidgets.QLineEdit(wheel_bipedal7d_data_monitor)
        self.lineEdit_6.setGeometry(QtCore.QRect(40, 160, 60, 25))
        self.lineEdit_6.setReadOnly(True)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.lineEdit_3 = QtWidgets.QLineEdit(wheel_bipedal7d_data_monitor)
        self.lineEdit_3.setGeometry(QtCore.QRect(40, 40, 60, 25))
        self.lineEdit_3.setReadOnly(True)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_2 = QtWidgets.QLabel(wheel_bipedal7d_data_monitor)
        self.label_2.setGeometry(QtCore.QRect(10, 0, 30, 17))
        self.label_2.setObjectName("label_2")
        self.label_10 = QtWidgets.QLabel(wheel_bipedal7d_data_monitor)
        self.label_10.setGeometry(QtCore.QRect(110, 120, 40, 17))
        self.label_10.setObjectName("label_10")
        self.label_5 = QtWidgets.QLabel(wheel_bipedal7d_data_monitor)
        self.label_5.setGeometry(QtCore.QRect(10, 160, 30, 17))
        self.label_5.setObjectName("label_5")
        self.label_3 = QtWidgets.QLabel(wheel_bipedal7d_data_monitor)
        self.label_3.setGeometry(QtCore.QRect(10, 80, 30, 17))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(wheel_bipedal7d_data_monitor)
        self.label_4.setGeometry(QtCore.QRect(10, 120, 30, 17))
        self.label_4.setObjectName("label_4")
        self.label_8 = QtWidgets.QLabel(wheel_bipedal7d_data_monitor)
        self.label_8.setGeometry(QtCore.QRect(110, 40, 40, 17))
        self.label_8.setObjectName("label_8")
        self.lineEdit_2 = QtWidgets.QLineEdit(wheel_bipedal7d_data_monitor)
        self.lineEdit_2.setGeometry(QtCore.QRect(40, 0, 60, 25))
        self.lineEdit_2.setReadOnly(True)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_5 = QtWidgets.QLineEdit(wheel_bipedal7d_data_monitor)
        self.lineEdit_5.setGeometry(QtCore.QRect(40, 80, 60, 25))
        self.lineEdit_5.setReadOnly(True)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.label_6 = QtWidgets.QLabel(wheel_bipedal7d_data_monitor)
        self.label_6.setGeometry(QtCore.QRect(110, 0, 40, 17))
        self.label_6.setObjectName("label_6")
        self.label_11 = QtWidgets.QLabel(wheel_bipedal7d_data_monitor)
        self.label_11.setGeometry(QtCore.QRect(110, 160, 40, 17))
        self.label_11.setObjectName("label_11")
        self.lineEdit_4 = QtWidgets.QLineEdit(wheel_bipedal7d_data_monitor)
        self.lineEdit_4.setGeometry(QtCore.QRect(40, 120, 60, 25))
        self.lineEdit_4.setReadOnly(True)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_12 = QtWidgets.QLabel(wheel_bipedal7d_data_monitor)
        self.label_12.setGeometry(QtCore.QRect(110, 200, 40, 17))
        self.label_12.setObjectName("label_12")
        self.lineEdit_7 = QtWidgets.QLineEdit(wheel_bipedal7d_data_monitor)
        self.lineEdit_7.setGeometry(QtCore.QRect(40, 200, 60, 25))
        self.lineEdit_7.setReadOnly(True)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.label_13 = QtWidgets.QLabel(wheel_bipedal7d_data_monitor)
        self.label_13.setGeometry(QtCore.QRect(10, 200, 30, 17))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(wheel_bipedal7d_data_monitor)
        self.label_14.setGeometry(QtCore.QRect(110, 240, 40, 17))
        self.label_14.setObjectName("label_14")
        self.lineEdit_8 = QtWidgets.QLineEdit(wheel_bipedal7d_data_monitor)
        self.lineEdit_8.setGeometry(QtCore.QRect(40, 240, 60, 25))
        self.lineEdit_8.setReadOnly(True)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.label_15 = QtWidgets.QLabel(wheel_bipedal7d_data_monitor)
        self.label_15.setGeometry(QtCore.QRect(10, 240, 30, 17))
        self.label_15.setObjectName("label_15")

        self.retranslateUi(wheel_bipedal7d_data_monitor)
        QtCore.QMetaObject.connectSlotsByName(wheel_bipedal7d_data_monitor)

    def retranslateUi(self, wheel_bipedal7d_data_monitor):
        _translate = QtCore.QCoreApplication.translate
        wheel_bipedal7d_data_monitor.setWindowTitle(_translate("wheel_bipedal7d_data_monitor", "数据监控"))
        self.label_9.setText(_translate("wheel_bipedal7d_data_monitor", "deg"))
        self.label_7.setText(_translate("wheel_bipedal7d_data_monitor", "T2"))
        self.label_2.setText(_translate("wheel_bipedal7d_data_monitor", "I1"))
        self.label_10.setText(_translate("wheel_bipedal7d_data_monitor", "deg"))
        self.label_5.setText(_translate("wheel_bipedal7d_data_monitor", "T5"))
        self.label_3.setText(_translate("wheel_bipedal7d_data_monitor", "T3"))
        self.label_4.setText(_translate("wheel_bipedal7d_data_monitor", "I4"))
        self.label_8.setText(_translate("wheel_bipedal7d_data_monitor", "deg"))
        self.label_6.setText(_translate("wheel_bipedal7d_data_monitor", "deg"))
        self.label_11.setText(_translate("wheel_bipedal7d_data_monitor", "deg"))
        self.label_12.setText(_translate("wheel_bipedal7d_data_monitor", "deg"))
        self.label_13.setText(_translate("wheel_bipedal7d_data_monitor", "T6"))
        self.label_14.setText(_translate("wheel_bipedal7d_data_monitor", "deg"))
        self.label_15.setText(_translate("wheel_bipedal7d_data_monitor", "I7"))

